---
title: "p8105_hw6_cl3664_p1"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
```

Column {data-width=450}
-----------------------------------------------------------------------

### Sales by department

```{r read}
cart = read_csv("./data/instacart_train_data.csv.zip")

```

```{r chartA}
cart%>%
  filter(department != "missing")%>%
  group_by(department)%>%
  mutate(sales = n())%>%
  distinct(department,.keep_all=TRUE)%>%
  ungroup(department)%>%
  mutate(department = fct_reorder(as.factor(department),sales))%>%
  mutate(hover=str_c(department," Sales:$",sales))%>%
  plot_ly(x = ~department, y = ~sales, type = "bar", color=~department, text=~hover, alpha = 0.5)
```


Column {data-width=550}
-----------------------------------------------------------------------

### "Busy days" in a week

```{r chartB}
cart%>%
  filter(department != "missing")%>%
  mutate(order_dow = order_dow+1)%>%
  group_by(order_dow, department)%>%
  mutate(sales = n(),
         hover = str_c(department))%>%
  plot_ly(x=~order_dow, y=~sales, type = "scatter", color = ~department, text = ~hover, mode = "line")
```




### "Busy time" by department

```{r chartC}
cart%>%
  filter(department != "missing")%>%
  group_by(department)%>%
  mutate(median_hour=median(order_hour_of_day))%>%
  ungroup(department)%>%
  mutate(department = fct_reorder(department,median_hour))%>%
  plot_ly(x = ~department, y = ~order_hour_of_day, type = "box", color=~department, alpha = 0.5)
```

